### ISSUE TITLE
As a user I would like to have a time tracking system built into the tasks so that it is easier to tell how long something will take or is taking to complete and how much time I have spent on the task

### ISSUE THREAD

**Issue by aneuhold** [PointSpire/PointSpire#56]
- [ ] AC 1: The user can add an estimated time to tasks
- [ ] AC 2: The user is able to start and stop a timer that records the time passing
- [ ] AC 3: The user is able to edit the amount of time that has passed
- [ ] AC 4: The amount of time passed for sub-tasks is accumulated up to the higher level tasks

Schema idea:

```
Task: {
  timeTracking: {
    lastStartTime: Date
    paused: boolean
    currentTimeCounter: TimeFromSomeLibrary? Moment.js?
    estimatedTime: Time
  }
}
```

Then when the timer is started, it sends a call to the server to update the lastStartTime to the current time and paused to false.

When they pause the time, the lastStartTime is used to determine difference between that date and now, which is added to currentTimeCounter, then paused is set to true.
